server:
  port: 8080

spring:

  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java

  servlet:
    multipart:
      #设置单个文件的最大值
      max-file-size: 10MB

      #设置单次请求文件最大值
      max-request-size: 10MB

  aop:
    #开启切面编程
    auto: true

  main:
    allow-bean-definition-overriding: true

  redis:  #redis配置
    host: 129.204.74.133
    port: 6379
    jedis:
      pool:
        max-idle: 15
        min-idle: 10
        max-active: 20

  datasource:
    username: root
    password: Mail123456
    #&nullCatalogMeansCurrent=true 指代工作流在扫描的时候只扫描当前数据库，没有表则创建表 不要去扫描所有数据库
    url: jdbc:mysql://129.204.74.133:3306/jiangnanship?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#进行数据加密
  #spring.encrypt.responseEncryptUriList[1]=/encryptEntity
  #spring.encrypt.responseEncryptUriList[2]=/save
  #spring.encrypt.responseEncryptUriList[3]=/encryptEntityXml
  #spring.encrypt.responseEncryptUriList[4]=/decryptEntityXml
  #spring.encrypt.urlPatterns[0]=/user/*
  #spring.encrypt.urlPatterns[1]=/save/*
  #spring.encrypt.requestDecyptUriIgnoreList[0]=/save
  #spring.encrypt.responseEncryptUriIgnoreList[0]=/encryptEntity
  #spring.encrypt.responseEncryptUriIgnoreList[1]=/save
  encrypt:
    #base64定义的key
    key: shujujiamibase64
    responseEncryptUriList[0]: /encryptStr

#    #前端表格传过来时间格式化
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
#
#  #针对json格式前端时间格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8


#mybatis配置
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: com.caidao.entity
  # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#fastdfs 配置类
fdfs:
  so-timeout: 6000 #超时时间
  connect-timeout: 6000 #连接超时时间
  thumb-image: #缩略图
    width: 20
    height: 20
  tracker-list: #踪迹服务器tracker地址
    - 129.204.74.133:22122

#自定义图片显示前缀路径
fdfs-imgUpload-prifax: http://129.204.74.133:8888/