server:
  port: 8080

spring:

  servlet:
    multipart:
      #设置单个文件的最大值
      max-file-size: 50MB

      #设置单次请求文件最大值
      max-request-size: 50MB

  aop:
    #开启切面编程
    auto: true

  main:
    allow-bean-definition-overriding: true

  redis:  #redis配置
    host: 129.204.74.133
    port: 6379
    jedis:
      pool:
        max-idle: 15
        min-idle: 10
        max-active: 20

  datasource:
    username: root
    password: Mail123456
    #&nullCatalogMeansCurrent=true 指代工作流在扫描的时候只扫描当前数据库，没有表则创建表 不要去扫描所有数据库
    url: jdbc:mysql://129.204.74.133:3306/jiangnanship?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis配置
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: com.caidao.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger2 配置
swagger2:
  base-package: com.caidao.controller
  name: jinpeng
  url: https://www.baidu.com
  email: 245311344@qq.com
  title: mail-shop的数据接口
  destription: 数据认证
  term-of-service-url: www.yanli.ltd
  license: Apache 2.0

#fastdfs 配置类
fdfs:
  so-timeout: 6000 #超时时间
  connect-timeout: 6000 #连接超时时间
  thumb-image: #缩略图
    width: 20
    height: 20
  tracker-list: #踪迹服务器tracker地址
    - 129.204.74.133:22122


